#*****************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# uart_core_interface.tcl: Tcl script for re-creating project 'uart_core_interface'
#
# Generated by Vivado on Tue Jul 25 10:45:31 CEST 2023
# IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (uart_core_interface.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/debug_uart_receiver.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/debug_uart_sm_fsm.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/debug_uart_transmitter.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/fifo_async.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/fifo_mem.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/fifo_rptr_empty.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/fifo_sync_r2w.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/fifo_sync_w2r.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/fifo_wptr_full.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/mux8_1_8bit.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/timeoutrst_module.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/vivado/src/hdl/debug_uart_core_struct.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/uart_core_interface.srcs/sources_1/bd/uart_core/uart_core.bd"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/uart_core_interface.srcs/sources_1/bd/uart_core/hdl/uart_core_wrapper.v"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/uart_core_interface.srcs/constrs_1/new/uart_core_constraints.xdc"
#    "/run/media/dcs/data2/workspaces/uart_core_interface/uart_core_interface.srcs/sim_1/new/enable_sr_tb.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
   "$origin_dir/src/hdl/debug_uart_receiver.v" \
   "$origin_dir/src/hdl/debug_uart_sm_fsm.v" \
   "$origin_dir/src/hdl/debug_uart_transmitter.v" \
   "$origin_dir/src/hdl/fifo_async.v" \
   "$origin_dir/src/hdl/fifo_mem.v" \
   "$origin_dir/src/hdl/fifo_rptr_empty.v" \
   "$origin_dir/src/hdl/fifo_sync_r2w.v" \
   "$origin_dir/src/hdl/fifo_sync_w2r.v" \
   "$origin_dir/src/hdl/fifo_wptr_full.v" \
   "$origin_dir/src/hdl/mux8_1_8bit.v" \
   "$origin_dir/src/hdl/timeoutrst_module.v" \
   "$origin_dir/src/hdl/debug_uart_core_struct.v" \
   #>>>>>>>>>>>>>>>>Edited by Qamesh>>>>>>>>>>>>>>>>
   #remove the lines that import the HDL wrapper file and the block design (.bd) file into the project.
   #"$origin_dir/../uart_core_interface.srcs/sources_1/bd/uart_core/uart_core.bd" \
   #"$origin_dir/../uart_core_interface.srcs/sources_1/bd/uart_core/hdl/uart_core_wrapper.v" \
   "$origin_dir/../uart_core_interface.srcs/constrs_1/new/uart_core_constraints.xdc" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# # Set the reference directory for source file relative paths (by default the value is script directory path)
# set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "uart_core_interface"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "uart_core_interface.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}
#>>>>>>>>>>>>>>>>Edited by Qamesh>>>>>>>>>>>>>>>>  
# Set the directory path for the original project from where this script was exported
#set orig_proj_dir "[file normalize "$origin_dir/../"]"
set origin_dir [file dirname [info script]]
set src_folder [file join $origin_dir "src"]
set ip_folder [file join $origin_dir "ip_repo"]

  
# Create project
#create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xczu9eg-ffvb1156-2-e
create_project ${_xil_proj_name_} $origin_dir/${_xil_proj_name_}  -part xczu9eg-ffvb1156-2-e

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}



# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:zcu102:part0:3.3" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "zcu102" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "16" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "16" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "16" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "16" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "16" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "16" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "16" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}
# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/hdl/debug_uart_receiver.v" ]\
 [file normalize "${origin_dir}/src/hdl/debug_uart_sm_fsm.v" ]\
 [file normalize "${origin_dir}/src/hdl/debug_uart_transmitter.v" ]\
 [file normalize "${origin_dir}/src/hdl/fifo_async.v" ]\
 [file normalize "${origin_dir}/src/hdl/fifo_mem.v" ]\
 [file normalize "${origin_dir}/src/hdl/fifo_rptr_empty.v" ]\
 [file normalize "${origin_dir}/src/hdl/fifo_sync_r2w.v" ]\
 [file normalize "${origin_dir}/src/hdl/fifo_sync_w2r.v" ]\
 [file normalize "${origin_dir}/src/hdl/fifo_wptr_full.v" ]\
 [file normalize "${origin_dir}/src/hdl/mux8_1_8bit.v" ]\
 [file normalize "${origin_dir}/src/hdl/timeoutrst_module.v" ]\
 [file normalize "${origin_dir}/src/hdl/debug_uart_core_struct.v" ]\
]


# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
#>>>>>>>>>>>>>>>>Edited by Qamesh>>>>>>>>>>>>>>>>
#set file "uart_core/uart_core.bd"
#set file "${origin_dir}/src/bd/uart_core.bd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "registered_with_manager" -value "1" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "uart_core_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize ${origin_dir}/../uart_core_interface.srcs/constrs_1/new/uart_core_constraints.xdc]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/uart_core_constraints.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
#>>>>>>>>>>>>>>>>Edited by Qamesh>>>>>>>>>>>>>>>> Replace /new/ with /imports/new/
# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "$proj_dir/${_xil_proj_name_}.srcs/constrs_1/imports/new/uart_core_constraints.xdc" -objects $obj
set_property -name "target_ucf" -value "$proj_dir/${_xil_proj_name_}.srcs/constrs_1/imports/new/uart_core_constraints.xdc" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "enable_sr_tb" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]



#>>>>>>>>>>>>>>>>Edited by Qamesh>>>>>>>>>>>>>>>>
# Create block design
source $origin_dir/src/bd/uart_core.tcl
#source $origin_dir/src/bd/uart_core_bd.tcl

 # Generate the wrapper
 set design_name [get_bd_designs]
 make_wrapper -files [get_files $design_name.bd] -top -import
